It's a complete mess
mantisg/React-App-Stuff pull request #22
Opened 2023-04-03 23:06 UTC by mantisg

This code has gotten out of hand. I can't wait to rewrite it, but I want to understand why what I'm doing here isn't working first. I need to know. If you can find why it's not working, let me know where the problem is and I'll look for myself and find the fix for it.

2023-04-03 23:43 UTC, marques-j-robinson requested changes
I do see the error and have a fully functioning version on my computer right now.

2023-04-03 23:43 UTC, marques-j-robinson commented on src/Components/App.jsx
> -    }, [])
This change is the issue.
[Documentation](https://codedamn.com/news/reactjs/useeffect-dependency)

2023-04-04 15:55 UTC, mantisg commented
I can not believe I took out that dependency array and didn't put it back in. So silly

2023-04-04 16:39 UTC, mantisg commented
Ok, so what I've done with this latest commit is try to separate history among all the games being played by setting the history when games are pulled to each game's specific history. However, the array that comes from the API is not being read. I have console logged it and isolated it. History logs as:
```JSON
[[null, null, null, null, null, null, null, null, null]]
```
When history is listed as:
```JSON
[null, null, null, null, null, null, null, null, null]
```
it works fine. When you add the wrapping array when there are no moves, the code can't process array functions on it like it should, considering the array of arrays format is how history ends up after some moves are made.

2023-04-08 00:34 UTC, merged